name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        # The JDK version to make available on the path. Required to run any clojure command line tools.
        # You can use any package that providing any JDK here, eg. `actions/setup-java@v1`
        # or you can use mine package to provision graalvm on hosted environment.
    - uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: graal setup
      uses: DeLaGuardo/setup-graalvm@3.0
      with:
       graalvm-version: '19.3.1.java11'

    - run: gu install native-image

    - name: clojure setup
      uses: DeLaGuardo/setup-clojure@3.1
      with:
                # To use Clojure CLI 1.10.1.561 based on tools.deps
        cli: '1.10.1.469'
    - run: clojure -Sdescribe
    - run: clojure -Sdeps "{:deps {seancorfield/depstar {:mvn/version \"1.1.136\"}}}" -M:depstar -m hf.depstar.uberjar -C -m ggsoft.git.core  clj-ci-utils.jar

    - uses: actions/upload-artifact@v2
      with:
        path: clj-ci-utils.jar
